### PR TITLE
Added homepage countdown.

### PR DESCRIPTION
**Pull request by jc-hiroto**

### CODE REVIEW

**Review by swh00tw — COMMENTED** [review]
WML... no, I mean GJ. Color-changing feature is very coooooooool!!

**Comment by swh00tw** [comment]
Don't forget to clear console messages & warnings

**Comment by jc-hiroto** [comment]
> WML... no, I mean GJ. Color-changing feature is very coooooooool!!

I'm glad that you found this feature m8 ☺️

**Comment by jc-hiroto** [comment]
✔️ Cleaned warnings and logs.

**Pull request merged**
