### PR TITLE
Refactor/drag and drop feature

### PR DESCRIPTION
**Pull request by swh00tw**
Since `react-sortable-hoc` will be deprecated in the future React's version, switch to newer package `dnd-kit`.

### CODE REVIEW

**Review by jc-hiroto — CHANGES_REQUESTED** [review]
There are some issues when trying to drag using mobile devices.
Here are some related resources:
https://docs.dndkit.com/api-documentation/draggable#recommendations
https://stackoverflow.com/questions/70795676/touch-users-cant-drag-and-drop-in-react-app

**Comment by jc-hiroto** [comment]
https://github.com/atlassian/react-beautiful-dnd
Maybe this can be a good choice since it's open-sourced by Atlassian who acquired Trello.

**Review by Klay24-Huang — APPROVED** [review]
ok

**Review by jc-hiroto — CHANGES_REQUESTED** [review]
Nice job!
But there's a minor issue when I try to rearrange the courses in the table view. My other courses just disappeared after I saved my changes, only the one I'm changing remains.
You should check that out and this branch should be good to go.

**Review by jc-hiroto — APPROVED** [review]
LGTM

**Pull request merged**
