### PR TITLE
Refactor/error page direct routing blocking

### PR DESCRIPTION
**Pull request by swh00tw**

### CODE REVIEW

**Comment by swh00tw** [comment]
Solution reference: 
- https://stackoverflow.com/a/52138179/17420003
- https://stackoverflow.com/questions/42173786/react-router-pass-data-when-navigating-programmatically

Sol: 
**Classify user is come from directly accessing to this page by URL or by useNavigation in our catch error blocks**
Pass a "state" when need to navigate to error page in our error handling blocks.
When render error page, inspect the "state". 
If the value is null (no state when directly access url), redirect to home page. 
Else, render error page.

**Comment by jc-hiroto** [comment]
Nice! Let me implement the logging function then we can merge it.

**Comment by swh00tw** [comment]
Great. Let me add redirect when refresh the error page :D

**Review by jc-hiroto — APPROVED** [review]
Nice work ❤️

**Review by Wil0408 — APPROVED** [review]
Nice work!

**Pull request merged**
